export const BULK_ACTION_QUEUE = 'BULK_ACTION_QUEUE'
export const BULK_ACTION_JOB = 'PROCESS_BULK_ACTION'
export const BATCH_PROCESSING_QUEUE = 'BATCH_PROCESSING_QUEUE'
export const PROCESS_BATCH_JOB = 'PROCESS_BATCH'